services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_USER: postgres
      DB_HOST: db
      DB_NAME: postgres
      DB_PASS: root
      DB_PORT: 5432

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
